micronaut:
    application:
        name: receipt-processor
redis:
    uri: redis://localhost
netty:
    default:
        allocator:
            max-order: 3
logger:
    levels:
        dev.receipt.processor: DEBUG
